package com.juin.report.dao.mapper;

import com.juin.report.dao.domain.Assents;
import com.juin.report.dao.domain.AssentsCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AssentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int countByExample(AssentsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int deleteByExample(AssentsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int insert(Assents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int insertSelective(Assents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    List<Assents> selectByExampleWithRowbounds(AssentsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    List<Assents> selectByExample(AssentsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    Assents selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Assents record, @Param("example") AssentsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Assents record, @Param("example") AssentsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Assents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    int updateByPrimaryKey(Assents record);
}