package com.juin.report.dao.mapper;

import com.juin.report.dao.domain.Flow;
import com.juin.report.dao.domain.FlowCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface FlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int countByExample(FlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int deleteByExample(FlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int insert(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int insertSelective(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    List<Flow> selectByExampleWithRowbounds(FlowCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    List<Flow> selectByExample(FlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    Flow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") Flow record, @Param("example") FlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int updateByExample(@Param("record") Flow record, @Param("example") FlowCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int updateByPrimaryKeySelective(Flow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Tue Jun 25 23:21:35 CST 2019
     */
    int updateByPrimaryKey(Flow record);
}