package com.juin.report.dao.mapper;

import com.juin.report.dao.domain.Liabilities;
import com.juin.report.dao.domain.LiabilitiesCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface LiabilitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int countByExample(LiabilitiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int deleteByExample(LiabilitiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int insert(Liabilities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int insertSelective(Liabilities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    List<Liabilities> selectByExampleWithRowbounds(LiabilitiesCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    List<Liabilities> selectByExample(LiabilitiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    Liabilities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") Liabilities record, @Param("example") LiabilitiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int updateByExample(@Param("record") Liabilities record, @Param("example") LiabilitiesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int updateByPrimaryKeySelective(Liabilities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    int updateByPrimaryKey(Liabilities record);
}