package com.juin.report.dao.mapper;

import com.juin.report.dao.domain.Profit;
import com.juin.report.dao.domain.ProfitCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int countByExample(ProfitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int deleteByExample(ProfitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int insert(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int insertSelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    List<Profit> selectByExampleWithRowbounds(ProfitCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    List<Profit> selectByExample(ProfitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    Profit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Profit record, @Param("example") ProfitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Profit record, @Param("example") ProfitCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Profit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    int updateByPrimaryKey(Profit record);
}