package com.juin.report.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Assents implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.id
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.org_name
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private String org_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.status
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.month
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private Date month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.money_funds
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal money_funds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.trading_financial_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal trading_financial_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.notes_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal notes_receivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal receivables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.prepayment
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal prepayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.interest_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal interest_receivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.dividends_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal dividends_receivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.other_receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal other_receivables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.inventory
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal inventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.non_current_assets_12m
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal non_current_assets_12m;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.other_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal other_current_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.total_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal total_current_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.financial_assets_available_for_sale
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal financial_assets_available_for_sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.hold_investment_due
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal hold_investment_due;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.long_term_equity_investment
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal long_term_equity_investment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.long_term_receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal long_term_receivables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.investment_property
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal investment_property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.fixed_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal fixed_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.construction_in_progress
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal construction_in_progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.engineering_material
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal engineering_material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.disposal_of_fixed_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal disposal_of_fixed_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.productive_biological_asset
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal productive_biological_asset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.oil_and_gas_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal oil_and_gas_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.intangible_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal intangible_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.development_expenditure
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal development_expenditure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.goodwill
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal goodwill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.long_term_unamortized_expenses
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal long_term_unamortized_expenses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.deferred_tax_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal deferred_tax_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.other_no_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal other_no_current_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.total_no_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal total_no_current_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.total_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private BigDecimal total_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.create_time
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_assets.last_update_time
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private Date last_update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.id
     *
     * @return the value of t_assets.id
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.id
     *
     * @param id the value for t_assets.id
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.org_name
     *
     * @return the value of t_assets.org_name
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public String getOrg_name() {
        return org_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.org_name
     *
     * @param org_name the value for t_assets.org_name
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setOrg_name(String org_name) {
        this.org_name = org_name == null ? null : org_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.status
     *
     * @return the value of t_assets.status
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.status
     *
     * @param status the value for t_assets.status
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.month
     *
     * @return the value of t_assets.month
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.month
     *
     * @param month the value for t_assets.month
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setMonth(Date month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.money_funds
     *
     * @return the value of t_assets.money_funds
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getMoney_funds() {
        return money_funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.money_funds
     *
     * @param money_funds the value for t_assets.money_funds
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setMoney_funds(BigDecimal money_funds) {
        this.money_funds = money_funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.trading_financial_assets
     *
     * @return the value of t_assets.trading_financial_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getTrading_financial_assets() {
        return trading_financial_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.trading_financial_assets
     *
     * @param trading_financial_assets the value for t_assets.trading_financial_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setTrading_financial_assets(BigDecimal trading_financial_assets) {
        this.trading_financial_assets = trading_financial_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.notes_receivable
     *
     * @return the value of t_assets.notes_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getNotes_receivable() {
        return notes_receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.notes_receivable
     *
     * @param notes_receivable the value for t_assets.notes_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setNotes_receivable(BigDecimal notes_receivable) {
        this.notes_receivable = notes_receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.receivables
     *
     * @return the value of t_assets.receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getReceivables() {
        return receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.receivables
     *
     * @param receivables the value for t_assets.receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setReceivables(BigDecimal receivables) {
        this.receivables = receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.prepayment
     *
     * @return the value of t_assets.prepayment
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getPrepayment() {
        return prepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.prepayment
     *
     * @param prepayment the value for t_assets.prepayment
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setPrepayment(BigDecimal prepayment) {
        this.prepayment = prepayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.interest_receivable
     *
     * @return the value of t_assets.interest_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getInterest_receivable() {
        return interest_receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.interest_receivable
     *
     * @param interest_receivable the value for t_assets.interest_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setInterest_receivable(BigDecimal interest_receivable) {
        this.interest_receivable = interest_receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.dividends_receivable
     *
     * @return the value of t_assets.dividends_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getDividends_receivable() {
        return dividends_receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.dividends_receivable
     *
     * @param dividends_receivable the value for t_assets.dividends_receivable
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setDividends_receivable(BigDecimal dividends_receivable) {
        this.dividends_receivable = dividends_receivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.other_receivables
     *
     * @return the value of t_assets.other_receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getOther_receivables() {
        return other_receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.other_receivables
     *
     * @param other_receivables the value for t_assets.other_receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setOther_receivables(BigDecimal other_receivables) {
        this.other_receivables = other_receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.inventory
     *
     * @return the value of t_assets.inventory
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.inventory
     *
     * @param inventory the value for t_assets.inventory
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setInventory(BigDecimal inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.non_current_assets_12m
     *
     * @return the value of t_assets.non_current_assets_12m
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getNon_current_assets_12m() {
        return non_current_assets_12m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.non_current_assets_12m
     *
     * @param non_current_assets_12m the value for t_assets.non_current_assets_12m
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setNon_current_assets_12m(BigDecimal non_current_assets_12m) {
        this.non_current_assets_12m = non_current_assets_12m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.other_current_assets
     *
     * @return the value of t_assets.other_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getOther_current_assets() {
        return other_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.other_current_assets
     *
     * @param other_current_assets the value for t_assets.other_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setOther_current_assets(BigDecimal other_current_assets) {
        this.other_current_assets = other_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.total_current_assets
     *
     * @return the value of t_assets.total_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getTotal_current_assets() {
        return total_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.total_current_assets
     *
     * @param total_current_assets the value for t_assets.total_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setTotal_current_assets(BigDecimal total_current_assets) {
        this.total_current_assets = total_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.financial_assets_available_for_sale
     *
     * @return the value of t_assets.financial_assets_available_for_sale
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getFinancial_assets_available_for_sale() {
        return financial_assets_available_for_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.financial_assets_available_for_sale
     *
     * @param financial_assets_available_for_sale the value for t_assets.financial_assets_available_for_sale
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setFinancial_assets_available_for_sale(BigDecimal financial_assets_available_for_sale) {
        this.financial_assets_available_for_sale = financial_assets_available_for_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.hold_investment_due
     *
     * @return the value of t_assets.hold_investment_due
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getHold_investment_due() {
        return hold_investment_due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.hold_investment_due
     *
     * @param hold_investment_due the value for t_assets.hold_investment_due
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setHold_investment_due(BigDecimal hold_investment_due) {
        this.hold_investment_due = hold_investment_due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.long_term_equity_investment
     *
     * @return the value of t_assets.long_term_equity_investment
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getLong_term_equity_investment() {
        return long_term_equity_investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.long_term_equity_investment
     *
     * @param long_term_equity_investment the value for t_assets.long_term_equity_investment
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setLong_term_equity_investment(BigDecimal long_term_equity_investment) {
        this.long_term_equity_investment = long_term_equity_investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.long_term_receivables
     *
     * @return the value of t_assets.long_term_receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getLong_term_receivables() {
        return long_term_receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.long_term_receivables
     *
     * @param long_term_receivables the value for t_assets.long_term_receivables
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setLong_term_receivables(BigDecimal long_term_receivables) {
        this.long_term_receivables = long_term_receivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.investment_property
     *
     * @return the value of t_assets.investment_property
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getInvestment_property() {
        return investment_property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.investment_property
     *
     * @param investment_property the value for t_assets.investment_property
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setInvestment_property(BigDecimal investment_property) {
        this.investment_property = investment_property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.fixed_assets
     *
     * @return the value of t_assets.fixed_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getFixed_assets() {
        return fixed_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.fixed_assets
     *
     * @param fixed_assets the value for t_assets.fixed_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setFixed_assets(BigDecimal fixed_assets) {
        this.fixed_assets = fixed_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.construction_in_progress
     *
     * @return the value of t_assets.construction_in_progress
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getConstruction_in_progress() {
        return construction_in_progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.construction_in_progress
     *
     * @param construction_in_progress the value for t_assets.construction_in_progress
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setConstruction_in_progress(BigDecimal construction_in_progress) {
        this.construction_in_progress = construction_in_progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.engineering_material
     *
     * @return the value of t_assets.engineering_material
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getEngineering_material() {
        return engineering_material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.engineering_material
     *
     * @param engineering_material the value for t_assets.engineering_material
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setEngineering_material(BigDecimal engineering_material) {
        this.engineering_material = engineering_material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.disposal_of_fixed_assets
     *
     * @return the value of t_assets.disposal_of_fixed_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getDisposal_of_fixed_assets() {
        return disposal_of_fixed_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.disposal_of_fixed_assets
     *
     * @param disposal_of_fixed_assets the value for t_assets.disposal_of_fixed_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setDisposal_of_fixed_assets(BigDecimal disposal_of_fixed_assets) {
        this.disposal_of_fixed_assets = disposal_of_fixed_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.productive_biological_asset
     *
     * @return the value of t_assets.productive_biological_asset
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getProductive_biological_asset() {
        return productive_biological_asset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.productive_biological_asset
     *
     * @param productive_biological_asset the value for t_assets.productive_biological_asset
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setProductive_biological_asset(BigDecimal productive_biological_asset) {
        this.productive_biological_asset = productive_biological_asset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.oil_and_gas_assets
     *
     * @return the value of t_assets.oil_and_gas_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getOil_and_gas_assets() {
        return oil_and_gas_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.oil_and_gas_assets
     *
     * @param oil_and_gas_assets the value for t_assets.oil_and_gas_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setOil_and_gas_assets(BigDecimal oil_and_gas_assets) {
        this.oil_and_gas_assets = oil_and_gas_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.intangible_assets
     *
     * @return the value of t_assets.intangible_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getIntangible_assets() {
        return intangible_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.intangible_assets
     *
     * @param intangible_assets the value for t_assets.intangible_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setIntangible_assets(BigDecimal intangible_assets) {
        this.intangible_assets = intangible_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.development_expenditure
     *
     * @return the value of t_assets.development_expenditure
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getDevelopment_expenditure() {
        return development_expenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.development_expenditure
     *
     * @param development_expenditure the value for t_assets.development_expenditure
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setDevelopment_expenditure(BigDecimal development_expenditure) {
        this.development_expenditure = development_expenditure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.goodwill
     *
     * @return the value of t_assets.goodwill
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getGoodwill() {
        return goodwill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.goodwill
     *
     * @param goodwill the value for t_assets.goodwill
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setGoodwill(BigDecimal goodwill) {
        this.goodwill = goodwill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.long_term_unamortized_expenses
     *
     * @return the value of t_assets.long_term_unamortized_expenses
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getLong_term_unamortized_expenses() {
        return long_term_unamortized_expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.long_term_unamortized_expenses
     *
     * @param long_term_unamortized_expenses the value for t_assets.long_term_unamortized_expenses
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setLong_term_unamortized_expenses(BigDecimal long_term_unamortized_expenses) {
        this.long_term_unamortized_expenses = long_term_unamortized_expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.deferred_tax_assets
     *
     * @return the value of t_assets.deferred_tax_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getDeferred_tax_assets() {
        return deferred_tax_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.deferred_tax_assets
     *
     * @param deferred_tax_assets the value for t_assets.deferred_tax_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setDeferred_tax_assets(BigDecimal deferred_tax_assets) {
        this.deferred_tax_assets = deferred_tax_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.other_no_current_assets
     *
     * @return the value of t_assets.other_no_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getOther_no_current_assets() {
        return other_no_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.other_no_current_assets
     *
     * @param other_no_current_assets the value for t_assets.other_no_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setOther_no_current_assets(BigDecimal other_no_current_assets) {
        this.other_no_current_assets = other_no_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.total_no_current_assets
     *
     * @return the value of t_assets.total_no_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getTotal_no_current_assets() {
        return total_no_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.total_no_current_assets
     *
     * @param total_no_current_assets the value for t_assets.total_no_current_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setTotal_no_current_assets(BigDecimal total_no_current_assets) {
        this.total_no_current_assets = total_no_current_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.total_assets
     *
     * @return the value of t_assets.total_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public BigDecimal getTotal_assets() {
        return total_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.total_assets
     *
     * @param total_assets the value for t_assets.total_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setTotal_assets(BigDecimal total_assets) {
        this.total_assets = total_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.create_time
     *
     * @return the value of t_assets.create_time
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.create_time
     *
     * @param create_time the value for t_assets.create_time
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_assets.last_update_time
     *
     * @return the value of t_assets.last_update_time
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public Date getLast_update_time() {
        return last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_assets.last_update_time
     *
     * @param last_update_time the value for t_assets.last_update_time
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    public void setLast_update_time(Date last_update_time) {
        this.last_update_time = last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_assets
     *
     * @mbggenerated Sat Jun 15 17:37:05 GMT+08:00 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", org_name=").append(org_name);
        sb.append(", status=").append(status);
        sb.append(", month=").append(month);
        sb.append(", money_funds=").append(money_funds);
        sb.append(", trading_financial_assets=").append(trading_financial_assets);
        sb.append(", notes_receivable=").append(notes_receivable);
        sb.append(", receivables=").append(receivables);
        sb.append(", prepayment=").append(prepayment);
        sb.append(", interest_receivable=").append(interest_receivable);
        sb.append(", dividends_receivable=").append(dividends_receivable);
        sb.append(", other_receivables=").append(other_receivables);
        sb.append(", inventory=").append(inventory);
        sb.append(", non_current_assets_12m=").append(non_current_assets_12m);
        sb.append(", other_current_assets=").append(other_current_assets);
        sb.append(", total_current_assets=").append(total_current_assets);
        sb.append(", financial_assets_available_for_sale=").append(financial_assets_available_for_sale);
        sb.append(", hold_investment_due=").append(hold_investment_due);
        sb.append(", long_term_equity_investment=").append(long_term_equity_investment);
        sb.append(", long_term_receivables=").append(long_term_receivables);
        sb.append(", investment_property=").append(investment_property);
        sb.append(", fixed_assets=").append(fixed_assets);
        sb.append(", construction_in_progress=").append(construction_in_progress);
        sb.append(", engineering_material=").append(engineering_material);
        sb.append(", disposal_of_fixed_assets=").append(disposal_of_fixed_assets);
        sb.append(", productive_biological_asset=").append(productive_biological_asset);
        sb.append(", oil_and_gas_assets=").append(oil_and_gas_assets);
        sb.append(", intangible_assets=").append(intangible_assets);
        sb.append(", development_expenditure=").append(development_expenditure);
        sb.append(", goodwill=").append(goodwill);
        sb.append(", long_term_unamortized_expenses=").append(long_term_unamortized_expenses);
        sb.append(", deferred_tax_assets=").append(deferred_tax_assets);
        sb.append(", other_no_current_assets=").append(other_no_current_assets);
        sb.append(", total_no_current_assets=").append(total_no_current_assets);
        sb.append(", total_assets=").append(total_assets);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_update_time=").append(last_update_time);
        sb.append("]");
        return sb.toString();
    }
}