package com.juin.report.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Flow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.id
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.org_name
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private String org_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.month
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_flow_from_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_flow_from_operating_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.selling_goods_and_providing_services_cash
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal selling_goods_and_providing_services_cash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.refun_of_tax_levies
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal refun_of_tax_levies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.other_cash_related_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal other_cash_related_operating_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_inflows_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_inflows_operating_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_payment_for_goods_and_services
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_payment_for_goods_and_services;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_paid_employees
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_paid_employees;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.tax_payments
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal tax_payments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.payment_other_cash_related_business_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal payment_other_cash_related_business_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_outflow_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_outflow_operating_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_cash_flow_from_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_cash_flow_from_operating_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_flow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_flow_from_investment_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.proceeds_from_sell_of_investment
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal proceeds_from_sell_of_investment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_received_on_investment_income
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_received_on_investment_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_cash_fixed_intangible_other_long_term_assets
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_cash_fixed_intangible_other_long_term_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_cash_by_subsidiaries_and_other_business_units
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_cash_by_subsidiaries_and_other_business_units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.other_cash_related_to_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal other_cash_related_to_investment_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_inflow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_inflow_from_investment_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_paid_fixed_intangible_other_long_term_assets
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_paid_fixed_intangible_other_long_term_assets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_paid_for_investment
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_paid_for_investment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_cash_paid_by_subsidiaries_and_other_business_units
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_cash_paid_by_subsidiaries_and_other_business_units;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.pay_other_cash_related_to_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal pay_other_cash_related_to_investment_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_outflow_for_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_outflow_for_investment_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_cash_flow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_cash_flow_from_investment_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_flow_from_fundraising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_flow_from_fundraising_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.receipts_equity_securities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal receipts_equity_securities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.subsidiaries_receive_cash_from_minority_investors
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal subsidiaries_receive_cash_from_minority_investors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.receipts_from_loan
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal receipts_from_loan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.receipt_of_other_cash_related_fund_raising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal receipt_of_other_cash_related_fund_raising_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_inflow_from_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_inflow_from_financing_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.payment_for_debt
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal payment_for_debt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_to_distribute_dividends_or_pay_interest
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_to_distribute_dividends_or_pay_interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.dividends_paid_by_subsidiary_to_minority_shareholders
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal dividends_paid_by_subsidiary_to_minority_shareholders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.payment_of_other_cash_related_fund_raising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal payment_of_other_cash_related_fund_raising_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.cash_outflow_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal cash_outflow_financing_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_cash_flow_from_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_cash_flow_from_financing_activities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.effect_of_exchange_rate_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal effect_of_exchange_rate_and_cash_equivalents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.net_increase_in_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal net_increase_in_cash_and_cash_equivalents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.beginning_balance_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal beginning_balance_cash_and_cash_equivalents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.ending_balance_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private BigDecimal ending_balance_cash_and_cash_equivalents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.create_date
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private Date create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flow.last_update_date
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private Date last_update_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_flow
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.id
     *
     * @return the value of t_flow.id
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.id
     *
     * @param id the value for t_flow.id
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.org_name
     *
     * @return the value of t_flow.org_name
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public String getOrg_name() {
        return org_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.org_name
     *
     * @param org_name the value for t_flow.org_name
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setOrg_name(String org_name) {
        this.org_name = org_name == null ? null : org_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.month
     *
     * @return the value of t_flow.month
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.month
     *
     * @param month the value for t_flow.month
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_flow_from_operating_activities
     *
     * @return the value of t_flow.cash_flow_from_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_flow_from_operating_activities() {
        return cash_flow_from_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_flow_from_operating_activities
     *
     * @param cash_flow_from_operating_activities the value for t_flow.cash_flow_from_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_flow_from_operating_activities(BigDecimal cash_flow_from_operating_activities) {
        this.cash_flow_from_operating_activities = cash_flow_from_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.selling_goods_and_providing_services_cash
     *
     * @return the value of t_flow.selling_goods_and_providing_services_cash
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getSelling_goods_and_providing_services_cash() {
        return selling_goods_and_providing_services_cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.selling_goods_and_providing_services_cash
     *
     * @param selling_goods_and_providing_services_cash the value for t_flow.selling_goods_and_providing_services_cash
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setSelling_goods_and_providing_services_cash(BigDecimal selling_goods_and_providing_services_cash) {
        this.selling_goods_and_providing_services_cash = selling_goods_and_providing_services_cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.refun_of_tax_levies
     *
     * @return the value of t_flow.refun_of_tax_levies
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getRefun_of_tax_levies() {
        return refun_of_tax_levies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.refun_of_tax_levies
     *
     * @param refun_of_tax_levies the value for t_flow.refun_of_tax_levies
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setRefun_of_tax_levies(BigDecimal refun_of_tax_levies) {
        this.refun_of_tax_levies = refun_of_tax_levies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.other_cash_related_operating_activities
     *
     * @return the value of t_flow.other_cash_related_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getOther_cash_related_operating_activities() {
        return other_cash_related_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.other_cash_related_operating_activities
     *
     * @param other_cash_related_operating_activities the value for t_flow.other_cash_related_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setOther_cash_related_operating_activities(BigDecimal other_cash_related_operating_activities) {
        this.other_cash_related_operating_activities = other_cash_related_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_inflows_operating_activities
     *
     * @return the value of t_flow.cash_inflows_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_inflows_operating_activities() {
        return cash_inflows_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_inflows_operating_activities
     *
     * @param cash_inflows_operating_activities the value for t_flow.cash_inflows_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_inflows_operating_activities(BigDecimal cash_inflows_operating_activities) {
        this.cash_inflows_operating_activities = cash_inflows_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_payment_for_goods_and_services
     *
     * @return the value of t_flow.cash_payment_for_goods_and_services
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_payment_for_goods_and_services() {
        return cash_payment_for_goods_and_services;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_payment_for_goods_and_services
     *
     * @param cash_payment_for_goods_and_services the value for t_flow.cash_payment_for_goods_and_services
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_payment_for_goods_and_services(BigDecimal cash_payment_for_goods_and_services) {
        this.cash_payment_for_goods_and_services = cash_payment_for_goods_and_services;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_paid_employees
     *
     * @return the value of t_flow.cash_paid_employees
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_paid_employees() {
        return cash_paid_employees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_paid_employees
     *
     * @param cash_paid_employees the value for t_flow.cash_paid_employees
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_paid_employees(BigDecimal cash_paid_employees) {
        this.cash_paid_employees = cash_paid_employees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.tax_payments
     *
     * @return the value of t_flow.tax_payments
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getTax_payments() {
        return tax_payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.tax_payments
     *
     * @param tax_payments the value for t_flow.tax_payments
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setTax_payments(BigDecimal tax_payments) {
        this.tax_payments = tax_payments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.payment_other_cash_related_business_activities
     *
     * @return the value of t_flow.payment_other_cash_related_business_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getPayment_other_cash_related_business_activities() {
        return payment_other_cash_related_business_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.payment_other_cash_related_business_activities
     *
     * @param payment_other_cash_related_business_activities the value for t_flow.payment_other_cash_related_business_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setPayment_other_cash_related_business_activities(BigDecimal payment_other_cash_related_business_activities) {
        this.payment_other_cash_related_business_activities = payment_other_cash_related_business_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_outflow_operating_activities
     *
     * @return the value of t_flow.cash_outflow_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_outflow_operating_activities() {
        return cash_outflow_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_outflow_operating_activities
     *
     * @param cash_outflow_operating_activities the value for t_flow.cash_outflow_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_outflow_operating_activities(BigDecimal cash_outflow_operating_activities) {
        this.cash_outflow_operating_activities = cash_outflow_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_cash_flow_from_operating_activities
     *
     * @return the value of t_flow.net_cash_flow_from_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_cash_flow_from_operating_activities() {
        return net_cash_flow_from_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_cash_flow_from_operating_activities
     *
     * @param net_cash_flow_from_operating_activities the value for t_flow.net_cash_flow_from_operating_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_cash_flow_from_operating_activities(BigDecimal net_cash_flow_from_operating_activities) {
        this.net_cash_flow_from_operating_activities = net_cash_flow_from_operating_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_flow_from_investment_activities
     *
     * @return the value of t_flow.cash_flow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_flow_from_investment_activities() {
        return cash_flow_from_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_flow_from_investment_activities
     *
     * @param cash_flow_from_investment_activities the value for t_flow.cash_flow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_flow_from_investment_activities(BigDecimal cash_flow_from_investment_activities) {
        this.cash_flow_from_investment_activities = cash_flow_from_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.proceeds_from_sell_of_investment
     *
     * @return the value of t_flow.proceeds_from_sell_of_investment
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getProceeds_from_sell_of_investment() {
        return proceeds_from_sell_of_investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.proceeds_from_sell_of_investment
     *
     * @param proceeds_from_sell_of_investment the value for t_flow.proceeds_from_sell_of_investment
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setProceeds_from_sell_of_investment(BigDecimal proceeds_from_sell_of_investment) {
        this.proceeds_from_sell_of_investment = proceeds_from_sell_of_investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_received_on_investment_income
     *
     * @return the value of t_flow.cash_received_on_investment_income
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_received_on_investment_income() {
        return cash_received_on_investment_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_received_on_investment_income
     *
     * @param cash_received_on_investment_income the value for t_flow.cash_received_on_investment_income
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_received_on_investment_income(BigDecimal cash_received_on_investment_income) {
        this.cash_received_on_investment_income = cash_received_on_investment_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_cash_fixed_intangible_other_long_term_assets
     *
     * @return the value of t_flow.net_cash_fixed_intangible_other_long_term_assets
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_cash_fixed_intangible_other_long_term_assets() {
        return net_cash_fixed_intangible_other_long_term_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_cash_fixed_intangible_other_long_term_assets
     *
     * @param net_cash_fixed_intangible_other_long_term_assets the value for t_flow.net_cash_fixed_intangible_other_long_term_assets
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_cash_fixed_intangible_other_long_term_assets(BigDecimal net_cash_fixed_intangible_other_long_term_assets) {
        this.net_cash_fixed_intangible_other_long_term_assets = net_cash_fixed_intangible_other_long_term_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_cash_by_subsidiaries_and_other_business_units
     *
     * @return the value of t_flow.net_cash_by_subsidiaries_and_other_business_units
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_cash_by_subsidiaries_and_other_business_units() {
        return net_cash_by_subsidiaries_and_other_business_units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_cash_by_subsidiaries_and_other_business_units
     *
     * @param net_cash_by_subsidiaries_and_other_business_units the value for t_flow.net_cash_by_subsidiaries_and_other_business_units
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_cash_by_subsidiaries_and_other_business_units(BigDecimal net_cash_by_subsidiaries_and_other_business_units) {
        this.net_cash_by_subsidiaries_and_other_business_units = net_cash_by_subsidiaries_and_other_business_units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.other_cash_related_to_investment_activities
     *
     * @return the value of t_flow.other_cash_related_to_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getOther_cash_related_to_investment_activities() {
        return other_cash_related_to_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.other_cash_related_to_investment_activities
     *
     * @param other_cash_related_to_investment_activities the value for t_flow.other_cash_related_to_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setOther_cash_related_to_investment_activities(BigDecimal other_cash_related_to_investment_activities) {
        this.other_cash_related_to_investment_activities = other_cash_related_to_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_inflow_from_investment_activities
     *
     * @return the value of t_flow.cash_inflow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_inflow_from_investment_activities() {
        return cash_inflow_from_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_inflow_from_investment_activities
     *
     * @param cash_inflow_from_investment_activities the value for t_flow.cash_inflow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_inflow_from_investment_activities(BigDecimal cash_inflow_from_investment_activities) {
        this.cash_inflow_from_investment_activities = cash_inflow_from_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_paid_fixed_intangible_other_long_term_assets
     *
     * @return the value of t_flow.cash_paid_fixed_intangible_other_long_term_assets
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_paid_fixed_intangible_other_long_term_assets() {
        return cash_paid_fixed_intangible_other_long_term_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_paid_fixed_intangible_other_long_term_assets
     *
     * @param cash_paid_fixed_intangible_other_long_term_assets the value for t_flow.cash_paid_fixed_intangible_other_long_term_assets
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_paid_fixed_intangible_other_long_term_assets(BigDecimal cash_paid_fixed_intangible_other_long_term_assets) {
        this.cash_paid_fixed_intangible_other_long_term_assets = cash_paid_fixed_intangible_other_long_term_assets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_paid_for_investment
     *
     * @return the value of t_flow.cash_paid_for_investment
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_paid_for_investment() {
        return cash_paid_for_investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_paid_for_investment
     *
     * @param cash_paid_for_investment the value for t_flow.cash_paid_for_investment
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_paid_for_investment(BigDecimal cash_paid_for_investment) {
        this.cash_paid_for_investment = cash_paid_for_investment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_cash_paid_by_subsidiaries_and_other_business_units
     *
     * @return the value of t_flow.net_cash_paid_by_subsidiaries_and_other_business_units
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_cash_paid_by_subsidiaries_and_other_business_units() {
        return net_cash_paid_by_subsidiaries_and_other_business_units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_cash_paid_by_subsidiaries_and_other_business_units
     *
     * @param net_cash_paid_by_subsidiaries_and_other_business_units the value for t_flow.net_cash_paid_by_subsidiaries_and_other_business_units
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_cash_paid_by_subsidiaries_and_other_business_units(BigDecimal net_cash_paid_by_subsidiaries_and_other_business_units) {
        this.net_cash_paid_by_subsidiaries_and_other_business_units = net_cash_paid_by_subsidiaries_and_other_business_units;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.pay_other_cash_related_to_investment_activities
     *
     * @return the value of t_flow.pay_other_cash_related_to_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getPay_other_cash_related_to_investment_activities() {
        return pay_other_cash_related_to_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.pay_other_cash_related_to_investment_activities
     *
     * @param pay_other_cash_related_to_investment_activities the value for t_flow.pay_other_cash_related_to_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setPay_other_cash_related_to_investment_activities(BigDecimal pay_other_cash_related_to_investment_activities) {
        this.pay_other_cash_related_to_investment_activities = pay_other_cash_related_to_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_outflow_for_investment_activities
     *
     * @return the value of t_flow.cash_outflow_for_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_outflow_for_investment_activities() {
        return cash_outflow_for_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_outflow_for_investment_activities
     *
     * @param cash_outflow_for_investment_activities the value for t_flow.cash_outflow_for_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_outflow_for_investment_activities(BigDecimal cash_outflow_for_investment_activities) {
        this.cash_outflow_for_investment_activities = cash_outflow_for_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_cash_flow_from_investment_activities
     *
     * @return the value of t_flow.net_cash_flow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_cash_flow_from_investment_activities() {
        return net_cash_flow_from_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_cash_flow_from_investment_activities
     *
     * @param net_cash_flow_from_investment_activities the value for t_flow.net_cash_flow_from_investment_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_cash_flow_from_investment_activities(BigDecimal net_cash_flow_from_investment_activities) {
        this.net_cash_flow_from_investment_activities = net_cash_flow_from_investment_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_flow_from_fundraising_activities
     *
     * @return the value of t_flow.cash_flow_from_fundraising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_flow_from_fundraising_activities() {
        return cash_flow_from_fundraising_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_flow_from_fundraising_activities
     *
     * @param cash_flow_from_fundraising_activities the value for t_flow.cash_flow_from_fundraising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_flow_from_fundraising_activities(BigDecimal cash_flow_from_fundraising_activities) {
        this.cash_flow_from_fundraising_activities = cash_flow_from_fundraising_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.receipts_equity_securities
     *
     * @return the value of t_flow.receipts_equity_securities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getReceipts_equity_securities() {
        return receipts_equity_securities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.receipts_equity_securities
     *
     * @param receipts_equity_securities the value for t_flow.receipts_equity_securities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setReceipts_equity_securities(BigDecimal receipts_equity_securities) {
        this.receipts_equity_securities = receipts_equity_securities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.subsidiaries_receive_cash_from_minority_investors
     *
     * @return the value of t_flow.subsidiaries_receive_cash_from_minority_investors
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getSubsidiaries_receive_cash_from_minority_investors() {
        return subsidiaries_receive_cash_from_minority_investors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.subsidiaries_receive_cash_from_minority_investors
     *
     * @param subsidiaries_receive_cash_from_minority_investors the value for t_flow.subsidiaries_receive_cash_from_minority_investors
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setSubsidiaries_receive_cash_from_minority_investors(BigDecimal subsidiaries_receive_cash_from_minority_investors) {
        this.subsidiaries_receive_cash_from_minority_investors = subsidiaries_receive_cash_from_minority_investors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.receipts_from_loan
     *
     * @return the value of t_flow.receipts_from_loan
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getReceipts_from_loan() {
        return receipts_from_loan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.receipts_from_loan
     *
     * @param receipts_from_loan the value for t_flow.receipts_from_loan
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setReceipts_from_loan(BigDecimal receipts_from_loan) {
        this.receipts_from_loan = receipts_from_loan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.receipt_of_other_cash_related_fund_raising_activities
     *
     * @return the value of t_flow.receipt_of_other_cash_related_fund_raising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getReceipt_of_other_cash_related_fund_raising_activities() {
        return receipt_of_other_cash_related_fund_raising_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.receipt_of_other_cash_related_fund_raising_activities
     *
     * @param receipt_of_other_cash_related_fund_raising_activities the value for t_flow.receipt_of_other_cash_related_fund_raising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setReceipt_of_other_cash_related_fund_raising_activities(BigDecimal receipt_of_other_cash_related_fund_raising_activities) {
        this.receipt_of_other_cash_related_fund_raising_activities = receipt_of_other_cash_related_fund_raising_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_inflow_from_financing_activities
     *
     * @return the value of t_flow.cash_inflow_from_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_inflow_from_financing_activities() {
        return cash_inflow_from_financing_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_inflow_from_financing_activities
     *
     * @param cash_inflow_from_financing_activities the value for t_flow.cash_inflow_from_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_inflow_from_financing_activities(BigDecimal cash_inflow_from_financing_activities) {
        this.cash_inflow_from_financing_activities = cash_inflow_from_financing_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.payment_for_debt
     *
     * @return the value of t_flow.payment_for_debt
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getPayment_for_debt() {
        return payment_for_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.payment_for_debt
     *
     * @param payment_for_debt the value for t_flow.payment_for_debt
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setPayment_for_debt(BigDecimal payment_for_debt) {
        this.payment_for_debt = payment_for_debt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_to_distribute_dividends_or_pay_interest
     *
     * @return the value of t_flow.cash_to_distribute_dividends_or_pay_interest
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_to_distribute_dividends_or_pay_interest() {
        return cash_to_distribute_dividends_or_pay_interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_to_distribute_dividends_or_pay_interest
     *
     * @param cash_to_distribute_dividends_or_pay_interest the value for t_flow.cash_to_distribute_dividends_or_pay_interest
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_to_distribute_dividends_or_pay_interest(BigDecimal cash_to_distribute_dividends_or_pay_interest) {
        this.cash_to_distribute_dividends_or_pay_interest = cash_to_distribute_dividends_or_pay_interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.dividends_paid_by_subsidiary_to_minority_shareholders
     *
     * @return the value of t_flow.dividends_paid_by_subsidiary_to_minority_shareholders
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getDividends_paid_by_subsidiary_to_minority_shareholders() {
        return dividends_paid_by_subsidiary_to_minority_shareholders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.dividends_paid_by_subsidiary_to_minority_shareholders
     *
     * @param dividends_paid_by_subsidiary_to_minority_shareholders the value for t_flow.dividends_paid_by_subsidiary_to_minority_shareholders
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setDividends_paid_by_subsidiary_to_minority_shareholders(BigDecimal dividends_paid_by_subsidiary_to_minority_shareholders) {
        this.dividends_paid_by_subsidiary_to_minority_shareholders = dividends_paid_by_subsidiary_to_minority_shareholders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.payment_of_other_cash_related_fund_raising_activities
     *
     * @return the value of t_flow.payment_of_other_cash_related_fund_raising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getPayment_of_other_cash_related_fund_raising_activities() {
        return payment_of_other_cash_related_fund_raising_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.payment_of_other_cash_related_fund_raising_activities
     *
     * @param payment_of_other_cash_related_fund_raising_activities the value for t_flow.payment_of_other_cash_related_fund_raising_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setPayment_of_other_cash_related_fund_raising_activities(BigDecimal payment_of_other_cash_related_fund_raising_activities) {
        this.payment_of_other_cash_related_fund_raising_activities = payment_of_other_cash_related_fund_raising_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.cash_outflow_financing_activities
     *
     * @return the value of t_flow.cash_outflow_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getCash_outflow_financing_activities() {
        return cash_outflow_financing_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.cash_outflow_financing_activities
     *
     * @param cash_outflow_financing_activities the value for t_flow.cash_outflow_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCash_outflow_financing_activities(BigDecimal cash_outflow_financing_activities) {
        this.cash_outflow_financing_activities = cash_outflow_financing_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_cash_flow_from_financing_activities
     *
     * @return the value of t_flow.net_cash_flow_from_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_cash_flow_from_financing_activities() {
        return net_cash_flow_from_financing_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_cash_flow_from_financing_activities
     *
     * @param net_cash_flow_from_financing_activities the value for t_flow.net_cash_flow_from_financing_activities
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_cash_flow_from_financing_activities(BigDecimal net_cash_flow_from_financing_activities) {
        this.net_cash_flow_from_financing_activities = net_cash_flow_from_financing_activities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.effect_of_exchange_rate_and_cash_equivalents
     *
     * @return the value of t_flow.effect_of_exchange_rate_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getEffect_of_exchange_rate_and_cash_equivalents() {
        return effect_of_exchange_rate_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.effect_of_exchange_rate_and_cash_equivalents
     *
     * @param effect_of_exchange_rate_and_cash_equivalents the value for t_flow.effect_of_exchange_rate_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setEffect_of_exchange_rate_and_cash_equivalents(BigDecimal effect_of_exchange_rate_and_cash_equivalents) {
        this.effect_of_exchange_rate_and_cash_equivalents = effect_of_exchange_rate_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.net_increase_in_cash_and_cash_equivalents
     *
     * @return the value of t_flow.net_increase_in_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getNet_increase_in_cash_and_cash_equivalents() {
        return net_increase_in_cash_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.net_increase_in_cash_and_cash_equivalents
     *
     * @param net_increase_in_cash_and_cash_equivalents the value for t_flow.net_increase_in_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setNet_increase_in_cash_and_cash_equivalents(BigDecimal net_increase_in_cash_and_cash_equivalents) {
        this.net_increase_in_cash_and_cash_equivalents = net_increase_in_cash_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.beginning_balance_cash_and_cash_equivalents
     *
     * @return the value of t_flow.beginning_balance_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getBeginning_balance_cash_and_cash_equivalents() {
        return beginning_balance_cash_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.beginning_balance_cash_and_cash_equivalents
     *
     * @param beginning_balance_cash_and_cash_equivalents the value for t_flow.beginning_balance_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setBeginning_balance_cash_and_cash_equivalents(BigDecimal beginning_balance_cash_and_cash_equivalents) {
        this.beginning_balance_cash_and_cash_equivalents = beginning_balance_cash_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.ending_balance_cash_and_cash_equivalents
     *
     * @return the value of t_flow.ending_balance_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public BigDecimal getEnding_balance_cash_and_cash_equivalents() {
        return ending_balance_cash_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.ending_balance_cash_and_cash_equivalents
     *
     * @param ending_balance_cash_and_cash_equivalents the value for t_flow.ending_balance_cash_and_cash_equivalents
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setEnding_balance_cash_and_cash_equivalents(BigDecimal ending_balance_cash_and_cash_equivalents) {
        this.ending_balance_cash_and_cash_equivalents = ending_balance_cash_and_cash_equivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.create_date
     *
     * @return the value of t_flow.create_date
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.create_date
     *
     * @param create_date the value for t_flow.create_date
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flow.last_update_date
     *
     * @return the value of t_flow.last_update_date
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public Date getLast_update_date() {
        return last_update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flow.last_update_date
     *
     * @param last_update_date the value for t_flow.last_update_date
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    public void setLast_update_date(Date last_update_date) {
        this.last_update_date = last_update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow
     *
     * @mbggenerated Mon Jun 24 15:29:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", org_name=").append(org_name);
        sb.append(", month=").append(month);
        sb.append(", cash_flow_from_operating_activities=").append(cash_flow_from_operating_activities);
        sb.append(", selling_goods_and_providing_services_cash=").append(selling_goods_and_providing_services_cash);
        sb.append(", refun_of_tax_levies=").append(refun_of_tax_levies);
        sb.append(", other_cash_related_operating_activities=").append(other_cash_related_operating_activities);
        sb.append(", cash_inflows_operating_activities=").append(cash_inflows_operating_activities);
        sb.append(", cash_payment_for_goods_and_services=").append(cash_payment_for_goods_and_services);
        sb.append(", cash_paid_employees=").append(cash_paid_employees);
        sb.append(", tax_payments=").append(tax_payments);
        sb.append(", payment_other_cash_related_business_activities=").append(payment_other_cash_related_business_activities);
        sb.append(", cash_outflow_operating_activities=").append(cash_outflow_operating_activities);
        sb.append(", net_cash_flow_from_operating_activities=").append(net_cash_flow_from_operating_activities);
        sb.append(", cash_flow_from_investment_activities=").append(cash_flow_from_investment_activities);
        sb.append(", proceeds_from_sell_of_investment=").append(proceeds_from_sell_of_investment);
        sb.append(", cash_received_on_investment_income=").append(cash_received_on_investment_income);
        sb.append(", net_cash_fixed_intangible_other_long_term_assets=").append(net_cash_fixed_intangible_other_long_term_assets);
        sb.append(", net_cash_by_subsidiaries_and_other_business_units=").append(net_cash_by_subsidiaries_and_other_business_units);
        sb.append(", other_cash_related_to_investment_activities=").append(other_cash_related_to_investment_activities);
        sb.append(", cash_inflow_from_investment_activities=").append(cash_inflow_from_investment_activities);
        sb.append(", cash_paid_fixed_intangible_other_long_term_assets=").append(cash_paid_fixed_intangible_other_long_term_assets);
        sb.append(", cash_paid_for_investment=").append(cash_paid_for_investment);
        sb.append(", net_cash_paid_by_subsidiaries_and_other_business_units=").append(net_cash_paid_by_subsidiaries_and_other_business_units);
        sb.append(", pay_other_cash_related_to_investment_activities=").append(pay_other_cash_related_to_investment_activities);
        sb.append(", cash_outflow_for_investment_activities=").append(cash_outflow_for_investment_activities);
        sb.append(", net_cash_flow_from_investment_activities=").append(net_cash_flow_from_investment_activities);
        sb.append(", cash_flow_from_fundraising_activities=").append(cash_flow_from_fundraising_activities);
        sb.append(", receipts_equity_securities=").append(receipts_equity_securities);
        sb.append(", subsidiaries_receive_cash_from_minority_investors=").append(subsidiaries_receive_cash_from_minority_investors);
        sb.append(", receipts_from_loan=").append(receipts_from_loan);
        sb.append(", receipt_of_other_cash_related_fund_raising_activities=").append(receipt_of_other_cash_related_fund_raising_activities);
        sb.append(", cash_inflow_from_financing_activities=").append(cash_inflow_from_financing_activities);
        sb.append(", payment_for_debt=").append(payment_for_debt);
        sb.append(", cash_to_distribute_dividends_or_pay_interest=").append(cash_to_distribute_dividends_or_pay_interest);
        sb.append(", dividends_paid_by_subsidiary_to_minority_shareholders=").append(dividends_paid_by_subsidiary_to_minority_shareholders);
        sb.append(", payment_of_other_cash_related_fund_raising_activities=").append(payment_of_other_cash_related_fund_raising_activities);
        sb.append(", cash_outflow_financing_activities=").append(cash_outflow_financing_activities);
        sb.append(", net_cash_flow_from_financing_activities=").append(net_cash_flow_from_financing_activities);
        sb.append(", effect_of_exchange_rate_and_cash_equivalents=").append(effect_of_exchange_rate_and_cash_equivalents);
        sb.append(", net_increase_in_cash_and_cash_equivalents=").append(net_increase_in_cash_and_cash_equivalents);
        sb.append(", beginning_balance_cash_and_cash_equivalents=").append(beginning_balance_cash_and_cash_equivalents);
        sb.append(", ending_balance_cash_and_cash_equivalents=").append(ending_balance_cash_and_cash_equivalents);
        sb.append(", create_date=").append(create_date);
        sb.append(", last_update_date=").append(last_update_date);
        sb.append("]");
        return sb.toString();
    }
}