package com.juin.report.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Liabilities implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.id
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.org_name
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private String org_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.status
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.month
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private Date month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.year_temp
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private String year_temp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.short_term_borrowing
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal short_term_borrowing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.trading_financial_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal trading_financial_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.notes_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal notes_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.accounts_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal accounts_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.deposit_received
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal deposit_received;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.employee_pay_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal employee_pay_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.tax_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal tax_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.accrual_interest_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal accrual_interest_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.dividends_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal dividends_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.other_payables
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal other_payables;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.non_current_liabilities_due_12m
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal non_current_liabilities_due_12m;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.other_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal other_current_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.total_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal total_current_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.long_term_borrowing
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal long_term_borrowing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.bonds_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal bonds_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.long_term_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal long_term_payable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.account_payable_special_funds
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal account_payable_special_funds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.anticipation_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal anticipation_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.deferred_income_tax_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal deferred_income_tax_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.other_non_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal other_non_current_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.total_non_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal total_non_current_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.total_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal total_liabilities;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.paicl_up_capital
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal paicl_up_capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.capital_reserve
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal capital_reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.treasury_stock
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal treasury_stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.earned_surplus
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal earned_surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.undistributed_profit
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal undistributed_profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.equity_attributable_parent_company
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal equity_attributable_parent_company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.minority_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal minority_equity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.total_shareholders_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal total_shareholders_equity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.total_liabilities_shareholders_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private BigDecimal total_liabilities_shareholders_equity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.create_time
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_liabilities.last_update_time
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private Date last_update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.id
     *
     * @return the value of t_liabilities.id
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.id
     *
     * @param id the value for t_liabilities.id
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.org_name
     *
     * @return the value of t_liabilities.org_name
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public String getOrg_name() {
        return org_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.org_name
     *
     * @param org_name the value for t_liabilities.org_name
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setOrg_name(String org_name) {
        this.org_name = org_name == null ? null : org_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.status
     *
     * @return the value of t_liabilities.status
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.status
     *
     * @param status the value for t_liabilities.status
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.month
     *
     * @return the value of t_liabilities.month
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.month
     *
     * @param month the value for t_liabilities.month
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setMonth(Date month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.year_temp
     *
     * @return the value of t_liabilities.year_temp
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public String getYear_temp() {
        return year_temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.year_temp
     *
     * @param year_temp the value for t_liabilities.year_temp
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setYear_temp(String year_temp) {
        this.year_temp = year_temp == null ? null : year_temp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.short_term_borrowing
     *
     * @return the value of t_liabilities.short_term_borrowing
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getShort_term_borrowing() {
        return short_term_borrowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.short_term_borrowing
     *
     * @param short_term_borrowing the value for t_liabilities.short_term_borrowing
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setShort_term_borrowing(BigDecimal short_term_borrowing) {
        this.short_term_borrowing = short_term_borrowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.trading_financial_liabilities
     *
     * @return the value of t_liabilities.trading_financial_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTrading_financial_liabilities() {
        return trading_financial_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.trading_financial_liabilities
     *
     * @param trading_financial_liabilities the value for t_liabilities.trading_financial_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTrading_financial_liabilities(BigDecimal trading_financial_liabilities) {
        this.trading_financial_liabilities = trading_financial_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.notes_payable
     *
     * @return the value of t_liabilities.notes_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getNotes_payable() {
        return notes_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.notes_payable
     *
     * @param notes_payable the value for t_liabilities.notes_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setNotes_payable(BigDecimal notes_payable) {
        this.notes_payable = notes_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.accounts_payable
     *
     * @return the value of t_liabilities.accounts_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getAccounts_payable() {
        return accounts_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.accounts_payable
     *
     * @param accounts_payable the value for t_liabilities.accounts_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setAccounts_payable(BigDecimal accounts_payable) {
        this.accounts_payable = accounts_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.deposit_received
     *
     * @return the value of t_liabilities.deposit_received
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getDeposit_received() {
        return deposit_received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.deposit_received
     *
     * @param deposit_received the value for t_liabilities.deposit_received
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setDeposit_received(BigDecimal deposit_received) {
        this.deposit_received = deposit_received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.employee_pay_payable
     *
     * @return the value of t_liabilities.employee_pay_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getEmployee_pay_payable() {
        return employee_pay_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.employee_pay_payable
     *
     * @param employee_pay_payable the value for t_liabilities.employee_pay_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setEmployee_pay_payable(BigDecimal employee_pay_payable) {
        this.employee_pay_payable = employee_pay_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.tax_payable
     *
     * @return the value of t_liabilities.tax_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTax_payable() {
        return tax_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.tax_payable
     *
     * @param tax_payable the value for t_liabilities.tax_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTax_payable(BigDecimal tax_payable) {
        this.tax_payable = tax_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.accrual_interest_payable
     *
     * @return the value of t_liabilities.accrual_interest_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getAccrual_interest_payable() {
        return accrual_interest_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.accrual_interest_payable
     *
     * @param accrual_interest_payable the value for t_liabilities.accrual_interest_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setAccrual_interest_payable(BigDecimal accrual_interest_payable) {
        this.accrual_interest_payable = accrual_interest_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.dividends_payable
     *
     * @return the value of t_liabilities.dividends_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getDividends_payable() {
        return dividends_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.dividends_payable
     *
     * @param dividends_payable the value for t_liabilities.dividends_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setDividends_payable(BigDecimal dividends_payable) {
        this.dividends_payable = dividends_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.other_payables
     *
     * @return the value of t_liabilities.other_payables
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getOther_payables() {
        return other_payables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.other_payables
     *
     * @param other_payables the value for t_liabilities.other_payables
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setOther_payables(BigDecimal other_payables) {
        this.other_payables = other_payables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.non_current_liabilities_due_12m
     *
     * @return the value of t_liabilities.non_current_liabilities_due_12m
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getNon_current_liabilities_due_12m() {
        return non_current_liabilities_due_12m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.non_current_liabilities_due_12m
     *
     * @param non_current_liabilities_due_12m the value for t_liabilities.non_current_liabilities_due_12m
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setNon_current_liabilities_due_12m(BigDecimal non_current_liabilities_due_12m) {
        this.non_current_liabilities_due_12m = non_current_liabilities_due_12m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.other_current_liabilities
     *
     * @return the value of t_liabilities.other_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getOther_current_liabilities() {
        return other_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.other_current_liabilities
     *
     * @param other_current_liabilities the value for t_liabilities.other_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setOther_current_liabilities(BigDecimal other_current_liabilities) {
        this.other_current_liabilities = other_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.total_current_liabilities
     *
     * @return the value of t_liabilities.total_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTotal_current_liabilities() {
        return total_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.total_current_liabilities
     *
     * @param total_current_liabilities the value for t_liabilities.total_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTotal_current_liabilities(BigDecimal total_current_liabilities) {
        this.total_current_liabilities = total_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.long_term_borrowing
     *
     * @return the value of t_liabilities.long_term_borrowing
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getLong_term_borrowing() {
        return long_term_borrowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.long_term_borrowing
     *
     * @param long_term_borrowing the value for t_liabilities.long_term_borrowing
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setLong_term_borrowing(BigDecimal long_term_borrowing) {
        this.long_term_borrowing = long_term_borrowing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.bonds_payable
     *
     * @return the value of t_liabilities.bonds_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getBonds_payable() {
        return bonds_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.bonds_payable
     *
     * @param bonds_payable the value for t_liabilities.bonds_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setBonds_payable(BigDecimal bonds_payable) {
        this.bonds_payable = bonds_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.long_term_payable
     *
     * @return the value of t_liabilities.long_term_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getLong_term_payable() {
        return long_term_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.long_term_payable
     *
     * @param long_term_payable the value for t_liabilities.long_term_payable
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setLong_term_payable(BigDecimal long_term_payable) {
        this.long_term_payable = long_term_payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.account_payable_special_funds
     *
     * @return the value of t_liabilities.account_payable_special_funds
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getAccount_payable_special_funds() {
        return account_payable_special_funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.account_payable_special_funds
     *
     * @param account_payable_special_funds the value for t_liabilities.account_payable_special_funds
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setAccount_payable_special_funds(BigDecimal account_payable_special_funds) {
        this.account_payable_special_funds = account_payable_special_funds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.anticipation_liabilities
     *
     * @return the value of t_liabilities.anticipation_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getAnticipation_liabilities() {
        return anticipation_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.anticipation_liabilities
     *
     * @param anticipation_liabilities the value for t_liabilities.anticipation_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setAnticipation_liabilities(BigDecimal anticipation_liabilities) {
        this.anticipation_liabilities = anticipation_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.deferred_income_tax_liabilities
     *
     * @return the value of t_liabilities.deferred_income_tax_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getDeferred_income_tax_liabilities() {
        return deferred_income_tax_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.deferred_income_tax_liabilities
     *
     * @param deferred_income_tax_liabilities the value for t_liabilities.deferred_income_tax_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setDeferred_income_tax_liabilities(BigDecimal deferred_income_tax_liabilities) {
        this.deferred_income_tax_liabilities = deferred_income_tax_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.other_non_current_liabilities
     *
     * @return the value of t_liabilities.other_non_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getOther_non_current_liabilities() {
        return other_non_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.other_non_current_liabilities
     *
     * @param other_non_current_liabilities the value for t_liabilities.other_non_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setOther_non_current_liabilities(BigDecimal other_non_current_liabilities) {
        this.other_non_current_liabilities = other_non_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.total_non_current_liabilities
     *
     * @return the value of t_liabilities.total_non_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTotal_non_current_liabilities() {
        return total_non_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.total_non_current_liabilities
     *
     * @param total_non_current_liabilities the value for t_liabilities.total_non_current_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTotal_non_current_liabilities(BigDecimal total_non_current_liabilities) {
        this.total_non_current_liabilities = total_non_current_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.total_liabilities
     *
     * @return the value of t_liabilities.total_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTotal_liabilities() {
        return total_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.total_liabilities
     *
     * @param total_liabilities the value for t_liabilities.total_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTotal_liabilities(BigDecimal total_liabilities) {
        this.total_liabilities = total_liabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.paicl_up_capital
     *
     * @return the value of t_liabilities.paicl_up_capital
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getPaicl_up_capital() {
        return paicl_up_capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.paicl_up_capital
     *
     * @param paicl_up_capital the value for t_liabilities.paicl_up_capital
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setPaicl_up_capital(BigDecimal paicl_up_capital) {
        this.paicl_up_capital = paicl_up_capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.capital_reserve
     *
     * @return the value of t_liabilities.capital_reserve
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getCapital_reserve() {
        return capital_reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.capital_reserve
     *
     * @param capital_reserve the value for t_liabilities.capital_reserve
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setCapital_reserve(BigDecimal capital_reserve) {
        this.capital_reserve = capital_reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.treasury_stock
     *
     * @return the value of t_liabilities.treasury_stock
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTreasury_stock() {
        return treasury_stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.treasury_stock
     *
     * @param treasury_stock the value for t_liabilities.treasury_stock
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTreasury_stock(BigDecimal treasury_stock) {
        this.treasury_stock = treasury_stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.earned_surplus
     *
     * @return the value of t_liabilities.earned_surplus
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getEarned_surplus() {
        return earned_surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.earned_surplus
     *
     * @param earned_surplus the value for t_liabilities.earned_surplus
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setEarned_surplus(BigDecimal earned_surplus) {
        this.earned_surplus = earned_surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.undistributed_profit
     *
     * @return the value of t_liabilities.undistributed_profit
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getUndistributed_profit() {
        return undistributed_profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.undistributed_profit
     *
     * @param undistributed_profit the value for t_liabilities.undistributed_profit
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setUndistributed_profit(BigDecimal undistributed_profit) {
        this.undistributed_profit = undistributed_profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.equity_attributable_parent_company
     *
     * @return the value of t_liabilities.equity_attributable_parent_company
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getEquity_attributable_parent_company() {
        return equity_attributable_parent_company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.equity_attributable_parent_company
     *
     * @param equity_attributable_parent_company the value for t_liabilities.equity_attributable_parent_company
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setEquity_attributable_parent_company(BigDecimal equity_attributable_parent_company) {
        this.equity_attributable_parent_company = equity_attributable_parent_company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.minority_equity
     *
     * @return the value of t_liabilities.minority_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getMinority_equity() {
        return minority_equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.minority_equity
     *
     * @param minority_equity the value for t_liabilities.minority_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setMinority_equity(BigDecimal minority_equity) {
        this.minority_equity = minority_equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.total_shareholders_equity
     *
     * @return the value of t_liabilities.total_shareholders_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTotal_shareholders_equity() {
        return total_shareholders_equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.total_shareholders_equity
     *
     * @param total_shareholders_equity the value for t_liabilities.total_shareholders_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTotal_shareholders_equity(BigDecimal total_shareholders_equity) {
        this.total_shareholders_equity = total_shareholders_equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.total_liabilities_shareholders_equity
     *
     * @return the value of t_liabilities.total_liabilities_shareholders_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public BigDecimal getTotal_liabilities_shareholders_equity() {
        return total_liabilities_shareholders_equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.total_liabilities_shareholders_equity
     *
     * @param total_liabilities_shareholders_equity the value for t_liabilities.total_liabilities_shareholders_equity
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setTotal_liabilities_shareholders_equity(BigDecimal total_liabilities_shareholders_equity) {
        this.total_liabilities_shareholders_equity = total_liabilities_shareholders_equity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.create_time
     *
     * @return the value of t_liabilities.create_time
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.create_time
     *
     * @param create_time the value for t_liabilities.create_time
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_liabilities.last_update_time
     *
     * @return the value of t_liabilities.last_update_time
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public Date getLast_update_time() {
        return last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_liabilities.last_update_time
     *
     * @param last_update_time the value for t_liabilities.last_update_time
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    public void setLast_update_time(Date last_update_time) {
        this.last_update_time = last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_liabilities
     *
     * @mbggenerated Thu Jun 27 19:50:53 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", org_name=").append(org_name);
        sb.append(", status=").append(status);
        sb.append(", month=").append(month);
        sb.append(", year_temp=").append(year_temp);
        sb.append(", short_term_borrowing=").append(short_term_borrowing);
        sb.append(", trading_financial_liabilities=").append(trading_financial_liabilities);
        sb.append(", notes_payable=").append(notes_payable);
        sb.append(", accounts_payable=").append(accounts_payable);
        sb.append(", deposit_received=").append(deposit_received);
        sb.append(", employee_pay_payable=").append(employee_pay_payable);
        sb.append(", tax_payable=").append(tax_payable);
        sb.append(", accrual_interest_payable=").append(accrual_interest_payable);
        sb.append(", dividends_payable=").append(dividends_payable);
        sb.append(", other_payables=").append(other_payables);
        sb.append(", non_current_liabilities_due_12m=").append(non_current_liabilities_due_12m);
        sb.append(", other_current_liabilities=").append(other_current_liabilities);
        sb.append(", total_current_liabilities=").append(total_current_liabilities);
        sb.append(", long_term_borrowing=").append(long_term_borrowing);
        sb.append(", bonds_payable=").append(bonds_payable);
        sb.append(", long_term_payable=").append(long_term_payable);
        sb.append(", account_payable_special_funds=").append(account_payable_special_funds);
        sb.append(", anticipation_liabilities=").append(anticipation_liabilities);
        sb.append(", deferred_income_tax_liabilities=").append(deferred_income_tax_liabilities);
        sb.append(", other_non_current_liabilities=").append(other_non_current_liabilities);
        sb.append(", total_non_current_liabilities=").append(total_non_current_liabilities);
        sb.append(", total_liabilities=").append(total_liabilities);
        sb.append(", paicl_up_capital=").append(paicl_up_capital);
        sb.append(", capital_reserve=").append(capital_reserve);
        sb.append(", treasury_stock=").append(treasury_stock);
        sb.append(", earned_surplus=").append(earned_surplus);
        sb.append(", undistributed_profit=").append(undistributed_profit);
        sb.append(", equity_attributable_parent_company=").append(equity_attributable_parent_company);
        sb.append(", minority_equity=").append(minority_equity);
        sb.append(", total_shareholders_equity=").append(total_shareholders_equity);
        sb.append(", total_liabilities_shareholders_equity=").append(total_liabilities_shareholders_equity);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_update_time=").append(last_update_time);
        sb.append("]");
        return sb.toString();
    }
}