package com.juin.report.dao.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProfitCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public ProfitCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrg_nameIsNull() {
            addCriterion("org_name is null");
            return (Criteria) this;
        }

        public Criteria andOrg_nameIsNotNull() {
            addCriterion("org_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrg_nameEqualTo(String value) {
            addCriterion("org_name =", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameNotEqualTo(String value) {
            addCriterion("org_name <>", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameGreaterThan(String value) {
            addCriterion("org_name >", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameGreaterThanOrEqualTo(String value) {
            addCriterion("org_name >=", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameLessThan(String value) {
            addCriterion("org_name <", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameLessThanOrEqualTo(String value) {
            addCriterion("org_name <=", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameLike(String value) {
            addCriterion("org_name like", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameNotLike(String value) {
            addCriterion("org_name not like", value, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameIn(List<String> values) {
            addCriterion("org_name in", values, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameNotIn(List<String> values) {
            addCriterion("org_name not in", values, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameBetween(String value1, String value2) {
            addCriterion("org_name between", value1, value2, "org_name");
            return (Criteria) this;
        }

        public Criteria andOrg_nameNotBetween(String value1, String value2) {
            addCriterion("org_name not between", value1, value2, "org_name");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("month is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("month is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(String value) {
            addCriterion("month =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(String value) {
            addCriterion("month <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(String value) {
            addCriterion("month >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(String value) {
            addCriterion("month >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(String value) {
            addCriterion("month <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(String value) {
            addCriterion("month <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLike(String value) {
            addCriterion("month like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotLike(String value) {
            addCriterion("month not like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<String> values) {
            addCriterion("month in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<String> values) {
            addCriterion("month not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(String value1, String value2) {
            addCriterion("month between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(String value1, String value2) {
            addCriterion("month not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeIsNull() {
            addCriterion("operating_income is null");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeIsNotNull() {
            addCriterion("operating_income is not null");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeEqualTo(BigDecimal value) {
            addCriterion("operating_income =", value, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeNotEqualTo(BigDecimal value) {
            addCriterion("operating_income <>", value, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeGreaterThan(BigDecimal value) {
            addCriterion("operating_income >", value, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_income >=", value, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeLessThan(BigDecimal value) {
            addCriterion("operating_income <", value, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_income <=", value, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeIn(List<BigDecimal> values) {
            addCriterion("operating_income in", values, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeNotIn(List<BigDecimal> values) {
            addCriterion("operating_income not in", values, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_income between", value1, value2, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_incomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_income not between", value1, value2, "operating_income");
            return (Criteria) this;
        }

        public Criteria andOperating_costsIsNull() {
            addCriterion("operating_costs is null");
            return (Criteria) this;
        }

        public Criteria andOperating_costsIsNotNull() {
            addCriterion("operating_costs is not null");
            return (Criteria) this;
        }

        public Criteria andOperating_costsEqualTo(BigDecimal value) {
            addCriterion("operating_costs =", value, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsNotEqualTo(BigDecimal value) {
            addCriterion("operating_costs <>", value, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsGreaterThan(BigDecimal value) {
            addCriterion("operating_costs >", value, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_costs >=", value, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsLessThan(BigDecimal value) {
            addCriterion("operating_costs <", value, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_costs <=", value, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsIn(List<BigDecimal> values) {
            addCriterion("operating_costs in", values, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsNotIn(List<BigDecimal> values) {
            addCriterion("operating_costs not in", values, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_costs between", value1, value2, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andOperating_costsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_costs not between", value1, value2, "operating_costs");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesIsNull() {
            addCriterion("business_tax_and_surcharges is null");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesIsNotNull() {
            addCriterion("business_tax_and_surcharges is not null");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesEqualTo(BigDecimal value) {
            addCriterion("business_tax_and_surcharges =", value, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesNotEqualTo(BigDecimal value) {
            addCriterion("business_tax_and_surcharges <>", value, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesGreaterThan(BigDecimal value) {
            addCriterion("business_tax_and_surcharges >", value, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("business_tax_and_surcharges >=", value, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesLessThan(BigDecimal value) {
            addCriterion("business_tax_and_surcharges <", value, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("business_tax_and_surcharges <=", value, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesIn(List<BigDecimal> values) {
            addCriterion("business_tax_and_surcharges in", values, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesNotIn(List<BigDecimal> values) {
            addCriterion("business_tax_and_surcharges not in", values, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("business_tax_and_surcharges between", value1, value2, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andBusiness_tax_and_surchargesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("business_tax_and_surcharges not between", value1, value2, "business_tax_and_surcharges");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesIsNull() {
            addCriterion("selling_expenses is null");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesIsNotNull() {
            addCriterion("selling_expenses is not null");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesEqualTo(BigDecimal value) {
            addCriterion("selling_expenses =", value, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesNotEqualTo(BigDecimal value) {
            addCriterion("selling_expenses <>", value, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesGreaterThan(BigDecimal value) {
            addCriterion("selling_expenses >", value, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("selling_expenses >=", value, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesLessThan(BigDecimal value) {
            addCriterion("selling_expenses <", value, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("selling_expenses <=", value, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesIn(List<BigDecimal> values) {
            addCriterion("selling_expenses in", values, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesNotIn(List<BigDecimal> values) {
            addCriterion("selling_expenses not in", values, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("selling_expenses between", value1, value2, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andSelling_expensesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("selling_expenses not between", value1, value2, "selling_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesIsNull() {
            addCriterion("manage_expenses is null");
            return (Criteria) this;
        }

        public Criteria andManage_expensesIsNotNull() {
            addCriterion("manage_expenses is not null");
            return (Criteria) this;
        }

        public Criteria andManage_expensesEqualTo(BigDecimal value) {
            addCriterion("manage_expenses =", value, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesNotEqualTo(BigDecimal value) {
            addCriterion("manage_expenses <>", value, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesGreaterThan(BigDecimal value) {
            addCriterion("manage_expenses >", value, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("manage_expenses >=", value, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesLessThan(BigDecimal value) {
            addCriterion("manage_expenses <", value, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("manage_expenses <=", value, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesIn(List<BigDecimal> values) {
            addCriterion("manage_expenses in", values, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesNotIn(List<BigDecimal> values) {
            addCriterion("manage_expenses not in", values, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("manage_expenses between", value1, value2, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andManage_expensesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("manage_expenses not between", value1, value2, "manage_expenses");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseIsNull() {
            addCriterion("financial_expense is null");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseIsNotNull() {
            addCriterion("financial_expense is not null");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseEqualTo(BigDecimal value) {
            addCriterion("financial_expense =", value, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseNotEqualTo(BigDecimal value) {
            addCriterion("financial_expense <>", value, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseGreaterThan(BigDecimal value) {
            addCriterion("financial_expense >", value, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("financial_expense >=", value, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseLessThan(BigDecimal value) {
            addCriterion("financial_expense <", value, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("financial_expense <=", value, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseIn(List<BigDecimal> values) {
            addCriterion("financial_expense in", values, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseNotIn(List<BigDecimal> values) {
            addCriterion("financial_expense not in", values, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("financial_expense between", value1, value2, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andFinancial_expenseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("financial_expense not between", value1, value2, "financial_expense");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossIsNull() {
            addCriterion("assets_impairment_loss is null");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossIsNotNull() {
            addCriterion("assets_impairment_loss is not null");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossEqualTo(BigDecimal value) {
            addCriterion("assets_impairment_loss =", value, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossNotEqualTo(BigDecimal value) {
            addCriterion("assets_impairment_loss <>", value, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossGreaterThan(BigDecimal value) {
            addCriterion("assets_impairment_loss >", value, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("assets_impairment_loss >=", value, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossLessThan(BigDecimal value) {
            addCriterion("assets_impairment_loss <", value, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossLessThanOrEqualTo(BigDecimal value) {
            addCriterion("assets_impairment_loss <=", value, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossIn(List<BigDecimal> values) {
            addCriterion("assets_impairment_loss in", values, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossNotIn(List<BigDecimal> values) {
            addCriterion("assets_impairment_loss not in", values, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("assets_impairment_loss between", value1, value2, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andAssets_impairment_lossNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("assets_impairment_loss not between", value1, value2, "assets_impairment_loss");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeIsNull() {
            addCriterion("changes_in_fair_net_income is null");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeIsNotNull() {
            addCriterion("changes_in_fair_net_income is not null");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeEqualTo(BigDecimal value) {
            addCriterion("changes_in_fair_net_income =", value, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeNotEqualTo(BigDecimal value) {
            addCriterion("changes_in_fair_net_income <>", value, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeGreaterThan(BigDecimal value) {
            addCriterion("changes_in_fair_net_income >", value, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("changes_in_fair_net_income >=", value, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeLessThan(BigDecimal value) {
            addCriterion("changes_in_fair_net_income <", value, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("changes_in_fair_net_income <=", value, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeIn(List<BigDecimal> values) {
            addCriterion("changes_in_fair_net_income in", values, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeNotIn(List<BigDecimal> values) {
            addCriterion("changes_in_fair_net_income not in", values, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("changes_in_fair_net_income between", value1, value2, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andChanges_in_fair_net_incomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("changes_in_fair_net_income not between", value1, value2, "changes_in_fair_net_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeIsNull() {
            addCriterion("investment_income is null");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeIsNotNull() {
            addCriterion("investment_income is not null");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeEqualTo(BigDecimal value) {
            addCriterion("investment_income =", value, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeNotEqualTo(BigDecimal value) {
            addCriterion("investment_income <>", value, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeGreaterThan(BigDecimal value) {
            addCriterion("investment_income >", value, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_income >=", value, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeLessThan(BigDecimal value) {
            addCriterion("investment_income <", value, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_income <=", value, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeIn(List<BigDecimal> values) {
            addCriterion("investment_income in", values, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeNotIn(List<BigDecimal> values) {
            addCriterion("investment_income not in", values, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_income between", value1, value2, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_incomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_income not between", value1, value2, "investment_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeIsNull() {
            addCriterion("investment_joint_ventures_income is null");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeIsNotNull() {
            addCriterion("investment_joint_ventures_income is not null");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeEqualTo(BigDecimal value) {
            addCriterion("investment_joint_ventures_income =", value, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeNotEqualTo(BigDecimal value) {
            addCriterion("investment_joint_ventures_income <>", value, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeGreaterThan(BigDecimal value) {
            addCriterion("investment_joint_ventures_income >", value, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_joint_ventures_income >=", value, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeLessThan(BigDecimal value) {
            addCriterion("investment_joint_ventures_income <", value, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("investment_joint_ventures_income <=", value, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeIn(List<BigDecimal> values) {
            addCriterion("investment_joint_ventures_income in", values, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeNotIn(List<BigDecimal> values) {
            addCriterion("investment_joint_ventures_income not in", values, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_joint_ventures_income between", value1, value2, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andInvestment_joint_ventures_incomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("investment_joint_ventures_income not between", value1, value2, "investment_joint_ventures_income");
            return (Criteria) this;
        }

        public Criteria andOperating_profitIsNull() {
            addCriterion("operating_profit is null");
            return (Criteria) this;
        }

        public Criteria andOperating_profitIsNotNull() {
            addCriterion("operating_profit is not null");
            return (Criteria) this;
        }

        public Criteria andOperating_profitEqualTo(BigDecimal value) {
            addCriterion("operating_profit =", value, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitNotEqualTo(BigDecimal value) {
            addCriterion("operating_profit <>", value, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitGreaterThan(BigDecimal value) {
            addCriterion("operating_profit >", value, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_profit >=", value, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitLessThan(BigDecimal value) {
            addCriterion("operating_profit <", value, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_profit <=", value, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitIn(List<BigDecimal> values) {
            addCriterion("operating_profit in", values, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitNotIn(List<BigDecimal> values) {
            addCriterion("operating_profit not in", values, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_profit between", value1, value2, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_profitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_profit not between", value1, value2, "operating_profit");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeIsNull() {
            addCriterion("operating_outer_income is null");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeIsNotNull() {
            addCriterion("operating_outer_income is not null");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeEqualTo(BigDecimal value) {
            addCriterion("operating_outer_income =", value, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeNotEqualTo(BigDecimal value) {
            addCriterion("operating_outer_income <>", value, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeGreaterThan(BigDecimal value) {
            addCriterion("operating_outer_income >", value, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_outer_income >=", value, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeLessThan(BigDecimal value) {
            addCriterion("operating_outer_income <", value, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_outer_income <=", value, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeIn(List<BigDecimal> values) {
            addCriterion("operating_outer_income in", values, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeNotIn(List<BigDecimal> values) {
            addCriterion("operating_outer_income not in", values, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_outer_income between", value1, value2, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_incomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_outer_income not between", value1, value2, "operating_outer_income");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costIsNull() {
            addCriterion("operating_outer_cost is null");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costIsNotNull() {
            addCriterion("operating_outer_cost is not null");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costEqualTo(BigDecimal value) {
            addCriterion("operating_outer_cost =", value, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costNotEqualTo(BigDecimal value) {
            addCriterion("operating_outer_cost <>", value, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costGreaterThan(BigDecimal value) {
            addCriterion("operating_outer_cost >", value, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_outer_cost >=", value, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costLessThan(BigDecimal value) {
            addCriterion("operating_outer_cost <", value, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costLessThanOrEqualTo(BigDecimal value) {
            addCriterion("operating_outer_cost <=", value, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costIn(List<BigDecimal> values) {
            addCriterion("operating_outer_cost in", values, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costNotIn(List<BigDecimal> values) {
            addCriterion("operating_outer_cost not in", values, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_outer_cost between", value1, value2, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andOperating_outer_costNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("operating_outer_cost not between", value1, value2, "operating_outer_cost");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossIsNull() {
            addCriterion("no_current_assent_loss is null");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossIsNotNull() {
            addCriterion("no_current_assent_loss is not null");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossEqualTo(BigDecimal value) {
            addCriterion("no_current_assent_loss =", value, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossNotEqualTo(BigDecimal value) {
            addCriterion("no_current_assent_loss <>", value, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossGreaterThan(BigDecimal value) {
            addCriterion("no_current_assent_loss >", value, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("no_current_assent_loss >=", value, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossLessThan(BigDecimal value) {
            addCriterion("no_current_assent_loss <", value, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossLessThanOrEqualTo(BigDecimal value) {
            addCriterion("no_current_assent_loss <=", value, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossIn(List<BigDecimal> values) {
            addCriterion("no_current_assent_loss in", values, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossNotIn(List<BigDecimal> values) {
            addCriterion("no_current_assent_loss not in", values, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("no_current_assent_loss between", value1, value2, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andNo_current_assent_lossNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("no_current_assent_loss not between", value1, value2, "no_current_assent_loss");
            return (Criteria) this;
        }

        public Criteria andTotal_profitIsNull() {
            addCriterion("total_profit is null");
            return (Criteria) this;
        }

        public Criteria andTotal_profitIsNotNull() {
            addCriterion("total_profit is not null");
            return (Criteria) this;
        }

        public Criteria andTotal_profitEqualTo(BigDecimal value) {
            addCriterion("total_profit =", value, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitNotEqualTo(BigDecimal value) {
            addCriterion("total_profit <>", value, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitGreaterThan(BigDecimal value) {
            addCriterion("total_profit >", value, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_profit >=", value, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitLessThan(BigDecimal value) {
            addCriterion("total_profit <", value, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_profit <=", value, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitIn(List<BigDecimal> values) {
            addCriterion("total_profit in", values, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitNotIn(List<BigDecimal> values) {
            addCriterion("total_profit not in", values, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_profit between", value1, value2, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTotal_profitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_profit not between", value1, value2, "total_profit");
            return (Criteria) this;
        }

        public Criteria andTax_costIsNull() {
            addCriterion("tax_cost is null");
            return (Criteria) this;
        }

        public Criteria andTax_costIsNotNull() {
            addCriterion("tax_cost is not null");
            return (Criteria) this;
        }

        public Criteria andTax_costEqualTo(BigDecimal value) {
            addCriterion("tax_cost =", value, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costNotEqualTo(BigDecimal value) {
            addCriterion("tax_cost <>", value, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costGreaterThan(BigDecimal value) {
            addCriterion("tax_cost >", value, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_cost >=", value, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costLessThan(BigDecimal value) {
            addCriterion("tax_cost <", value, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tax_cost <=", value, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costIn(List<BigDecimal> values) {
            addCriterion("tax_cost in", values, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costNotIn(List<BigDecimal> values) {
            addCriterion("tax_cost not in", values, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_cost between", value1, value2, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andTax_costNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax_cost not between", value1, value2, "tax_cost");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsIsNull() {
            addCriterion("retained_profits is null");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsIsNotNull() {
            addCriterion("retained_profits is not null");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsEqualTo(BigDecimal value) {
            addCriterion("retained_profits =", value, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsNotEqualTo(BigDecimal value) {
            addCriterion("retained_profits <>", value, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsGreaterThan(BigDecimal value) {
            addCriterion("retained_profits >", value, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("retained_profits >=", value, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsLessThan(BigDecimal value) {
            addCriterion("retained_profits <", value, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("retained_profits <=", value, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsIn(List<BigDecimal> values) {
            addCriterion("retained_profits in", values, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsNotIn(List<BigDecimal> values) {
            addCriterion("retained_profits not in", values, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retained_profits between", value1, value2, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profitsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retained_profits not between", value1, value2, "retained_profits");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyIsNull() {
            addCriterion("retained_profits_parent_company is null");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyIsNotNull() {
            addCriterion("retained_profits_parent_company is not null");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyEqualTo(BigDecimal value) {
            addCriterion("retained_profits_parent_company =", value, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyNotEqualTo(BigDecimal value) {
            addCriterion("retained_profits_parent_company <>", value, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyGreaterThan(BigDecimal value) {
            addCriterion("retained_profits_parent_company >", value, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("retained_profits_parent_company >=", value, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyLessThan(BigDecimal value) {
            addCriterion("retained_profits_parent_company <", value, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("retained_profits_parent_company <=", value, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyIn(List<BigDecimal> values) {
            addCriterion("retained_profits_parent_company in", values, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyNotIn(List<BigDecimal> values) {
            addCriterion("retained_profits_parent_company not in", values, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retained_profits_parent_company between", value1, value2, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andRetained_profits_parent_companyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("retained_profits_parent_company not between", value1, value2, "retained_profits_parent_company");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeIsNull() {
            addCriterion("minority_interest_income is null");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeIsNotNull() {
            addCriterion("minority_interest_income is not null");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeEqualTo(BigDecimal value) {
            addCriterion("minority_interest_income =", value, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeNotEqualTo(BigDecimal value) {
            addCriterion("minority_interest_income <>", value, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeGreaterThan(BigDecimal value) {
            addCriterion("minority_interest_income >", value, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("minority_interest_income >=", value, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeLessThan(BigDecimal value) {
            addCriterion("minority_interest_income <", value, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("minority_interest_income <=", value, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeIn(List<BigDecimal> values) {
            addCriterion("minority_interest_income in", values, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeNotIn(List<BigDecimal> values) {
            addCriterion("minority_interest_income not in", values, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("minority_interest_income between", value1, value2, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andMinority_interest_incomeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("minority_interest_income not between", value1, value2, "minority_interest_income");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareIsNull() {
            addCriterion("earnings_per_share is null");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareIsNotNull() {
            addCriterion("earnings_per_share is not null");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share =", value, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareNotEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share <>", value, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareGreaterThan(BigDecimal value) {
            addCriterion("earnings_per_share >", value, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share >=", value, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareLessThan(BigDecimal value) {
            addCriterion("earnings_per_share <", value, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share <=", value, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareIn(List<BigDecimal> values) {
            addCriterion("earnings_per_share in", values, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareNotIn(List<BigDecimal> values) {
            addCriterion("earnings_per_share not in", values, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings_per_share between", value1, value2, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_shareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings_per_share not between", value1, value2, "earnings_per_share");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicIsNull() {
            addCriterion("earnings_per_share_basic is null");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicIsNotNull() {
            addCriterion("earnings_per_share_basic is not null");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_basic =", value, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicNotEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_basic <>", value, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicGreaterThan(BigDecimal value) {
            addCriterion("earnings_per_share_basic >", value, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_basic >=", value, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicLessThan(BigDecimal value) {
            addCriterion("earnings_per_share_basic <", value, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicLessThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_basic <=", value, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicIn(List<BigDecimal> values) {
            addCriterion("earnings_per_share_basic in", values, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicNotIn(List<BigDecimal> values) {
            addCriterion("earnings_per_share_basic not in", values, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings_per_share_basic between", value1, value2, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_basicNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings_per_share_basic not between", value1, value2, "earnings_per_share_basic");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationIsNull() {
            addCriterion("earnings_per_share_attenuation is null");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationIsNotNull() {
            addCriterion("earnings_per_share_attenuation is not null");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_attenuation =", value, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationNotEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_attenuation <>", value, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationGreaterThan(BigDecimal value) {
            addCriterion("earnings_per_share_attenuation >", value, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_attenuation >=", value, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationLessThan(BigDecimal value) {
            addCriterion("earnings_per_share_attenuation <", value, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("earnings_per_share_attenuation <=", value, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationIn(List<BigDecimal> values) {
            addCriterion("earnings_per_share_attenuation in", values, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationNotIn(List<BigDecimal> values) {
            addCriterion("earnings_per_share_attenuation not in", values, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings_per_share_attenuation between", value1, value2, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andEarnings_per_share_attenuationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("earnings_per_share_attenuation not between", value1, value2, "earnings_per_share_attenuation");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_timeEqualTo(Date value) {
            addCriterion("create_time =", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThan(Date value) {
            addCriterion("create_time >", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThan(Date value) {
            addCriterion("create_time <", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeIn(List<Date> values) {
            addCriterion("create_time in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andCreate_timeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "create_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeLessThan(Date value) {
            addCriterion("last_update_time <", value, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "last_update_time");
            return (Criteria) this;
        }

        public Criteria andLast_update_timeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "last_update_time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_profit
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 25 22:56:42 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_profit
     *
     * @mbggenerated Tue Jun 25 22:56:42 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}