package com.juin.report.dao.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Profit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.id
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.org_name
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private String org_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.month
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.operating_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal operating_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.operating_costs
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal operating_costs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.business_tax_and_surcharges
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal business_tax_and_surcharges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.selling_expenses
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal selling_expenses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.manage_expenses
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal manage_expenses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.financial_expense
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal financial_expense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.assets_impairment_loss
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal assets_impairment_loss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.changes_in_fair_net_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal changes_in_fair_net_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.investment_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal investment_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.investment_joint_ventures_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal investment_joint_ventures_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.operating_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal operating_profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.operating_outer_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal operating_outer_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.no_current_assent_loss
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal no_current_assent_loss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.total_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal total_profit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.tax_cost
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal tax_cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.retained_profits
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal retained_profits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.retained_profits_parent_company
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal retained_profits_parent_company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.minority_interest_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal minority_interest_income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.earnings_per_share
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal earnings_per_share;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.earnings_per_share_basic
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal earnings_per_share_basic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.earnings_per_share_attenuation
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private BigDecimal earnings_per_share_attenuation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.create_time
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profit.last_update_time
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private Date last_update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.id
     *
     * @return the value of t_profit.id
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.id
     *
     * @param id the value for t_profit.id
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.org_name
     *
     * @return the value of t_profit.org_name
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public String getOrg_name() {
        return org_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.org_name
     *
     * @param org_name the value for t_profit.org_name
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setOrg_name(String org_name) {
        this.org_name = org_name == null ? null : org_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.month
     *
     * @return the value of t_profit.month
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.month
     *
     * @param month the value for t_profit.month
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.operating_income
     *
     * @return the value of t_profit.operating_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getOperating_income() {
        return operating_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.operating_income
     *
     * @param operating_income the value for t_profit.operating_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setOperating_income(BigDecimal operating_income) {
        this.operating_income = operating_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.operating_costs
     *
     * @return the value of t_profit.operating_costs
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getOperating_costs() {
        return operating_costs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.operating_costs
     *
     * @param operating_costs the value for t_profit.operating_costs
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setOperating_costs(BigDecimal operating_costs) {
        this.operating_costs = operating_costs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.business_tax_and_surcharges
     *
     * @return the value of t_profit.business_tax_and_surcharges
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getBusiness_tax_and_surcharges() {
        return business_tax_and_surcharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.business_tax_and_surcharges
     *
     * @param business_tax_and_surcharges the value for t_profit.business_tax_and_surcharges
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setBusiness_tax_and_surcharges(BigDecimal business_tax_and_surcharges) {
        this.business_tax_and_surcharges = business_tax_and_surcharges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.selling_expenses
     *
     * @return the value of t_profit.selling_expenses
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getSelling_expenses() {
        return selling_expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.selling_expenses
     *
     * @param selling_expenses the value for t_profit.selling_expenses
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setSelling_expenses(BigDecimal selling_expenses) {
        this.selling_expenses = selling_expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.manage_expenses
     *
     * @return the value of t_profit.manage_expenses
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getManage_expenses() {
        return manage_expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.manage_expenses
     *
     * @param manage_expenses the value for t_profit.manage_expenses
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setManage_expenses(BigDecimal manage_expenses) {
        this.manage_expenses = manage_expenses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.financial_expense
     *
     * @return the value of t_profit.financial_expense
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getFinancial_expense() {
        return financial_expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.financial_expense
     *
     * @param financial_expense the value for t_profit.financial_expense
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setFinancial_expense(BigDecimal financial_expense) {
        this.financial_expense = financial_expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.assets_impairment_loss
     *
     * @return the value of t_profit.assets_impairment_loss
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getAssets_impairment_loss() {
        return assets_impairment_loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.assets_impairment_loss
     *
     * @param assets_impairment_loss the value for t_profit.assets_impairment_loss
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setAssets_impairment_loss(BigDecimal assets_impairment_loss) {
        this.assets_impairment_loss = assets_impairment_loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.changes_in_fair_net_income
     *
     * @return the value of t_profit.changes_in_fair_net_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getChanges_in_fair_net_income() {
        return changes_in_fair_net_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.changes_in_fair_net_income
     *
     * @param changes_in_fair_net_income the value for t_profit.changes_in_fair_net_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setChanges_in_fair_net_income(BigDecimal changes_in_fair_net_income) {
        this.changes_in_fair_net_income = changes_in_fair_net_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.investment_income
     *
     * @return the value of t_profit.investment_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getInvestment_income() {
        return investment_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.investment_income
     *
     * @param investment_income the value for t_profit.investment_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setInvestment_income(BigDecimal investment_income) {
        this.investment_income = investment_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.investment_joint_ventures_income
     *
     * @return the value of t_profit.investment_joint_ventures_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getInvestment_joint_ventures_income() {
        return investment_joint_ventures_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.investment_joint_ventures_income
     *
     * @param investment_joint_ventures_income the value for t_profit.investment_joint_ventures_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setInvestment_joint_ventures_income(BigDecimal investment_joint_ventures_income) {
        this.investment_joint_ventures_income = investment_joint_ventures_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.operating_profit
     *
     * @return the value of t_profit.operating_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getOperating_profit() {
        return operating_profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.operating_profit
     *
     * @param operating_profit the value for t_profit.operating_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setOperating_profit(BigDecimal operating_profit) {
        this.operating_profit = operating_profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.operating_outer_income
     *
     * @return the value of t_profit.operating_outer_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getOperating_outer_income() {
        return operating_outer_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.operating_outer_income
     *
     * @param operating_outer_income the value for t_profit.operating_outer_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setOperating_outer_income(BigDecimal operating_outer_income) {
        this.operating_outer_income = operating_outer_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.no_current_assent_loss
     *
     * @return the value of t_profit.no_current_assent_loss
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getNo_current_assent_loss() {
        return no_current_assent_loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.no_current_assent_loss
     *
     * @param no_current_assent_loss the value for t_profit.no_current_assent_loss
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setNo_current_assent_loss(BigDecimal no_current_assent_loss) {
        this.no_current_assent_loss = no_current_assent_loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.total_profit
     *
     * @return the value of t_profit.total_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getTotal_profit() {
        return total_profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.total_profit
     *
     * @param total_profit the value for t_profit.total_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setTotal_profit(BigDecimal total_profit) {
        this.total_profit = total_profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.tax_cost
     *
     * @return the value of t_profit.tax_cost
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getTax_cost() {
        return tax_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.tax_cost
     *
     * @param tax_cost the value for t_profit.tax_cost
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setTax_cost(BigDecimal tax_cost) {
        this.tax_cost = tax_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.retained_profits
     *
     * @return the value of t_profit.retained_profits
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getRetained_profits() {
        return retained_profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.retained_profits
     *
     * @param retained_profits the value for t_profit.retained_profits
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setRetained_profits(BigDecimal retained_profits) {
        this.retained_profits = retained_profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.retained_profits_parent_company
     *
     * @return the value of t_profit.retained_profits_parent_company
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getRetained_profits_parent_company() {
        return retained_profits_parent_company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.retained_profits_parent_company
     *
     * @param retained_profits_parent_company the value for t_profit.retained_profits_parent_company
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setRetained_profits_parent_company(BigDecimal retained_profits_parent_company) {
        this.retained_profits_parent_company = retained_profits_parent_company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.minority_interest_income
     *
     * @return the value of t_profit.minority_interest_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getMinority_interest_income() {
        return minority_interest_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.minority_interest_income
     *
     * @param minority_interest_income the value for t_profit.minority_interest_income
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setMinority_interest_income(BigDecimal minority_interest_income) {
        this.minority_interest_income = minority_interest_income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.earnings_per_share
     *
     * @return the value of t_profit.earnings_per_share
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getEarnings_per_share() {
        return earnings_per_share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.earnings_per_share
     *
     * @param earnings_per_share the value for t_profit.earnings_per_share
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setEarnings_per_share(BigDecimal earnings_per_share) {
        this.earnings_per_share = earnings_per_share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.earnings_per_share_basic
     *
     * @return the value of t_profit.earnings_per_share_basic
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getEarnings_per_share_basic() {
        return earnings_per_share_basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.earnings_per_share_basic
     *
     * @param earnings_per_share_basic the value for t_profit.earnings_per_share_basic
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setEarnings_per_share_basic(BigDecimal earnings_per_share_basic) {
        this.earnings_per_share_basic = earnings_per_share_basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.earnings_per_share_attenuation
     *
     * @return the value of t_profit.earnings_per_share_attenuation
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public BigDecimal getEarnings_per_share_attenuation() {
        return earnings_per_share_attenuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.earnings_per_share_attenuation
     *
     * @param earnings_per_share_attenuation the value for t_profit.earnings_per_share_attenuation
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setEarnings_per_share_attenuation(BigDecimal earnings_per_share_attenuation) {
        this.earnings_per_share_attenuation = earnings_per_share_attenuation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.create_time
     *
     * @return the value of t_profit.create_time
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.create_time
     *
     * @param create_time the value for t_profit.create_time
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profit.last_update_time
     *
     * @return the value of t_profit.last_update_time
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public Date getLast_update_time() {
        return last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profit.last_update_time
     *
     * @param last_update_time the value for t_profit.last_update_time
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    public void setLast_update_time(Date last_update_time) {
        this.last_update_time = last_update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_profit
     *
     * @mbggenerated Sun Jun 16 11:02:48 GMT+08:00 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", org_name=").append(org_name);
        sb.append(", month=").append(month);
        sb.append(", operating_income=").append(operating_income);
        sb.append(", operating_costs=").append(operating_costs);
        sb.append(", business_tax_and_surcharges=").append(business_tax_and_surcharges);
        sb.append(", selling_expenses=").append(selling_expenses);
        sb.append(", manage_expenses=").append(manage_expenses);
        sb.append(", financial_expense=").append(financial_expense);
        sb.append(", assets_impairment_loss=").append(assets_impairment_loss);
        sb.append(", changes_in_fair_net_income=").append(changes_in_fair_net_income);
        sb.append(", investment_income=").append(investment_income);
        sb.append(", investment_joint_ventures_income=").append(investment_joint_ventures_income);
        sb.append(", operating_profit=").append(operating_profit);
        sb.append(", operating_outer_income=").append(operating_outer_income);
        sb.append(", no_current_assent_loss=").append(no_current_assent_loss);
        sb.append(", total_profit=").append(total_profit);
        sb.append(", tax_cost=").append(tax_cost);
        sb.append(", retained_profits=").append(retained_profits);
        sb.append(", retained_profits_parent_company=").append(retained_profits_parent_company);
        sb.append(", minority_interest_income=").append(minority_interest_income);
        sb.append(", earnings_per_share=").append(earnings_per_share);
        sb.append(", earnings_per_share_basic=").append(earnings_per_share_basic);
        sb.append(", earnings_per_share_attenuation=").append(earnings_per_share_attenuation);
        sb.append(", create_time=").append(create_time);
        sb.append(", last_update_time=").append(last_update_time);
        sb.append("]");
        return sb.toString();
    }
}